import LoginPage from "@/components/login/LoginPage"
import { Metadata } from "next"
export const metadata: Metadata = {
  title: 'UM || Login',
  description: 'Generated by create next app',
}
const login = () => {

  
  return (
    <>
      
      <LoginPage/>
    </>
  )
}

export default login